title: Woradanue Nakdee (Pleng)
description: Even though my previous experience was in film and TV production, I decided to change my career after learning how to code. I enjoy the analytical and problem solving aspects that came with coding.
I’m currently a graduate student in computer science and particularly interested in deep learning. I can work in both team and individual settings, with strong work ethic and drive to success.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
